name: Install Kustomize
description: Install a specific version of Kustomize and add it to the PATH
inputs:
  version:
    description: Version to install
    default: '3.5.4'
runs:
  using: node12
  main: bundle.js
